# Generated by Django 4.2.6 on 2023-10-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_automatedemail_email_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Fundraising Image"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "subject",
                    models.CharField(max_length=200, verbose_name="Email's Subject"),
                ),
                ("content", models.TextField(verbose_name="Email's Content")),
            ],
            options={
                "verbose_name": "Contact Form",
                "verbose_name_plural": "Contact Forms",
            },
        ),
    ]
