# Generated by Django 4.2.6 on 2023-10-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_contactform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactform",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Sender's Email"),
        ),
    ]
