# Generated by Django 4.2.6 on 2023-11-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_volunteer_notes_alter_volunteer_zip_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteerassignment",
            name="assigned_position",
            field=models.TextField(
                choices=[
                    ("Driver", "Driver"),
                    ("Cook", "Cook"),
                    ("Server", "Server"),
                    ("Dishwasher", "Dishwasher"),
                    ("Photographer", "Photographer"),
                    ("Leader", "Leader"),
                ],
                max_length=12,
            ),
        ),
    ]
