# Generated by Django 4.2.6 on 2024-02-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_volunteerassignment_assigned_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="last_applied",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Last Applied"
            ),
        ),
    ]
