# Generated by Django 4.2.6 on 2024-02-07 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_volunteer_last_applied"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="volunteerassignment",
            options={
                "verbose_name": "Volunteer Assignment",
                "verbose_name_plural": "Volunteers Assignments",
            },
        ),
    ]
