# Generated by Django 4.2.6 on 2024-02-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_volunteerassignment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteerassignment",
            name="reject_participation",
            field=models.BooleanField(
                default=False,
                help_text="Check to waitlist the applicant",
                verbose_name="Waitlist",
            ),
        ),
    ]
