# Generated by Django 4.2.6 on 2024-02-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0014_rename_reject_participation_volunteerassignment_waitlist_participation",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="automatedemail",
            name="email_type",
            field=models.TextField(
                choices=[
                    ("Registration", "Registration"),
                    ("Application", "Application"),
                    ("Approval", "Approval"),
                    ("Waitlist", "Waitlist"),
                    ("Withdrawal", "Withdrawal"),
                    ("Event_Cancellation", "Event Cancellation"),
                    ("Confirmation", "Confirmation"),
                    ("Form_Submission", "Form Submission"),
                ],
                max_length=25,
                unique=True,
                verbose_name="Email Type",
            ),
        ),
    ]
