# Generated by Django 4.2.6 on 2024-02-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_volunteerassignment_food_drop_off"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteerassignment",
            name="has_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
