# Generated by Django 4.2.6 on 2024-02-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_volunteerassignment_confirmation_message_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteerassignment",
            name="food_drop_off",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Cook will drop off the food",
                null=True,
                verbose_name="Food Is Dropped Off",
            ),
        ),
    ]
