# Generated by Django 4.2.6 on 2024-08-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_volunteerassignment_food_drop_off"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteeringevents",
            name="city",
            field=models.TextField(
                choices=[("Montreal", "Montreal"), ("Toronto", "Toronto")],
                default="Montreal",
                max_length=25,
            ),
        ),
    ]
