# Generated by Django 4.2.19 on 2025-02-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_remove_volunteerassignment_has_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteerassignment",
            name="confirm_participation",
            field=models.BooleanField(
                default=False,
                help_text="Gets checked if volunteer confirmed participation via a link",
                verbose_name="Volunteer Confirmed Participation",
            ),
        ),
    ]
