# Generated by Django 4.2.19 on 2025-04-09 16:08

import api.utilities.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_alter_volunteerassignment_attended"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteeringevents",
            name="body",
            field=models.TextField(
                default="Hey Future and Recurring Volunteers, This is our standard volunteering event! OPEN TO ALL! Please sign up for the position most suitable for you! We can't wait to see you out there💚",
                verbose_name="Event Description",
            ),
        ),
        migrations.AlterField(
            model_name="volunteeringevents",
            name="datetime",
            field=models.DateTimeField(
                default=api.utilities.model_utils.next_sunday_noon,
                help_text="24 hour clock",
                verbose_name="Date&Time",
            ),
        ),
        migrations.AlterField(
            model_name="volunteeringevents",
            name="end_time",
            field=models.TimeField(
                default=api.utilities.model_utils.next_sunday_14_30,
                help_text="24 hour clock",
                verbose_name="Ending Time",
            ),
        ),
        migrations.AlterField(
            model_name="volunteeringevents",
            name="title",
            field=models.CharField(
                default="OPEN TO EVERYONE💚", max_length=100, verbose_name="Event Title"
            ),
        ),
    ]
