# Generated by Django 4.2.19 on 2025-04-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_alter_volunteeringevents_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteeringevents",
            name="collab_code",
            field=models.CharField(
                blank=True,
                help_text="For collab events only!",
                max_length=8,
                null=True,
                verbose_name="Collaboration Code",
            ),
        ),
        migrations.AddField(
            model_name="volunteeringevents",
            name="is_colab",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Is it a collaboration event?",
                max_length=100,
                verbose_name="Collaboration Event",
            ),
        ),
    ]
